/**
 * DRAFT BACKFILL — DeviceCalibrationParameter.decimalPlaces
 * (Stage 1 proposal — 2026-09-08. NOT YET RUN. HARD STOP for review before Stage 2.)
 *
 * Replaces the uniform 0 placeholder on NUMBER-type DeviceCalibrationParameter
 * rows with a proposed per-parameter precision. See
 *   docs/module-specs/measurement-results/DecimalPlaces_Backfill_Proposal.md
 * for the full per-parameter evidence table and the flagged low-confidence list.
 *
 * EVIDENCE BASIS (read the report §2 first):
 *   - The 50 LK worksheets in docs/technician-docs/Lembar-Kerja/ are BLANK TEMPLATES —
 *     they contain NO technician-recorded example readings and NO reference-instrument
 *     resolution values. The only usable signals are (a) the fixed setpoint values
 *     printed in the measurement tables and (b) the numeric precision of the stated
 *     tolerance. Everything else is unit-convention inference.
 *   - 22 rows: setpoint-grounded.  19 rows: per-parameter override.
 *   - 447 rows: unit-convention fallback only (170 of them low confidence).
 *
 * IDEMPOTENT: only updates NUMBER-type rows whose decimalPlaces is still 0 or NULL.
 * A row already carrying a human-reviewed value (> 0, or explicitly re-set) is left
 * untouched. A clean re-run is a no-op.
 *
 * CONFIDENCE GATE: set MIN_CONFIDENCE=high|medium|low (default: medium) to control how
 * much of the proposal is applied. 'low' applies everything; 'high' applies only the
 * setpoint-grounded / strong-convention rows and leaves the rest at 0 for a later
 * human spot-check pass.
 *
 * Run (Stage 2, AFTER review):
 *   pnpm --filter @medcal/db generate
 *   MIN_CONFIDENCE=medium pnpm --filter @medcal/db exec tsx --env-file ../../.env prisma/backfill-decimal-places.ts
 */
import { prisma } from "../src/index";

type Confidence = "high" | "medium" | "low";

interface Proposal {
  code: string;
  decimalPlaces: number;
  confidence: Confidence;
  evidence: "setpoint" | "tolerance" | "override" | "convention";
}

const PROPOSALS: Proposal[] = [
  { code: "ACLV_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ACLV_CHAMBER_TEMP_DT1", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ACLV_CHAMBER_TEMP_DT2", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ACLV_CHAMBER_TEMP_DT3", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ACLV_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "ACLV_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ACLV_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ACLV_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "ACLV_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "ACLV_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ACLV_STER_TEMP_121", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ACLV_STER_TEMP_134", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ACLV_STER_TIME_121", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "ACLV_STER_TIME_134", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "AUD_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "AUD_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "AUD_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "AUD_FREQUENCY_RESPONSE_KANAN", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "AUD_FREQUENCY_RESPONSE_KIRI", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "AUD_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "AUD_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "AUD_PURE_TONE_LINEARITY_KANAN", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "AUD_PURE_TONE_LINEARITY_KIRI", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "AUD_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "AUD_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BBR_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BBR_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "BBR_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BBR_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BBR_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "BBR_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "BBR_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BBR_STORAGE_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BLNW_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BLNW_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "BLNW_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BLNW_HIGH_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BLNW_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BLNW_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "BLNW_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "BLNW_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BLNW_TEMP_CALIBRATION", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BPM_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BPM_DIASTOLIC", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "BPM_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "BPM_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BPM_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BPM_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "BPM_MAP", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "BPM_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "BPM_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BPM_SYSTOLIC", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "BREASTP_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BREASTP_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "BREASTP_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BREASTP_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BREASTP_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "BREASTP_MAX_VACUUM", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "BREASTP_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "BREASTP_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BREASTP_TIME_MAX_VACUUM", decimalPlaces: 0, confidence: "medium", evidence: "override" },
  { code: "BREASTP_VACUUM_GAUGE", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "BSC_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BSC_DOWNFLOW", decimalPlaces: 2, confidence: "high", evidence: "override" },
  { code: "BSC_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "BSC_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BSC_INFLOW", decimalPlaces: 2, confidence: "high", evidence: "override" },
  { code: "BSC_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BSC_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "BSC_LIGHT_INTENSITY_OFF", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "BSC_LIGHT_INTENSITY_ON", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "BSC_PARTICLE_COUNT", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "BSC_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "BSC_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BSC_SOUND_LEVEL_OFF", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "BSC_SOUND_LEVEL_ON", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "BSC_UV_RADIATION", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BSM_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BSM_DIASTOLIC", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "BSM_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "BSM_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "BSM_HEART_RATE", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "BSM_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BSM_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "BSM_MAP", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "BSM_RESP_RATE", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "BSM_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "BSM_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "BSM_SPO2", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "BSM_SYSTOLIC", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "CCHAIN_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "CCHAIN_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "CCHAIN_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "CCHAIN_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CCHAIN_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "CCHAIN_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "CCHAIN_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CCHAIN_STORAGE_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CENT_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "CENT_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "CENT_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "CENT_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CENT_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "CENT_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "CENT_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CENT_SPEED", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "CENT_TIME", decimalPlaces: 0, confidence: "medium", evidence: "override" },
  { code: "CPAP_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "CPAP_CONCENTRATION", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "CPAP_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "CPAP_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "CPAP_FLOW_RATE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CPAP_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CPAP_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "CPAP_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "CPAP_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CRFR_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "CRFR_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "CRFR_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "CRFR_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CRFR_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "CRFR_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "CRFR_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CRFR_SPEED", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "CRFR_STORAGE_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "CRFR_TIME", decimalPlaces: 0, confidence: "medium", evidence: "override" },
  { code: "DUNIT_AIR_SPRAY", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "DUNIT_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "DUNIT_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "DUNIT_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "DUNIT_HP_PRESSURE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "DUNIT_HP_SPEED_HIGH", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "DUNIT_HP_SPEED_LOW", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "DUNIT_ILLUMINANCE", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "DUNIT_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "DUNIT_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "DUNIT_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "DUNIT_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "DUNIT_SUCTION", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "DXRAY_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "DXRAY_COLLIMATION_DIAMETER", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "DXRAY_COLLIMATION_LENGTH", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "DXRAY_DOSE_LINEARITY", decimalPlaces: 2, confidence: "low", evidence: "convention" },
  { code: "DXRAY_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "DXRAY_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "DXRAY_EXPOSURE_TIME", decimalPlaces: 2, confidence: "medium", evidence: "override" },
  { code: "DXRAY_HVL_70KV", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "DXRAY_HVL_80KV", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "DXRAY_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "DXRAY_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "DXRAY_KV_ACCURACY", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "DXRAY_REPRODUCIBILITY", decimalPlaces: 2, confidence: "low", evidence: "convention" },
  { code: "DXRAY_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "DXRAY_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "EBED_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "EBED_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "EBED_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "EBED_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "EBED_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "EBED_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "EBED_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ECG_AMPLITUDE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ECG_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ECG_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "ECG_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ECG_HR_CAL", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "ECG_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ECG_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "ECG_NORMAL_TEST", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ECG_REC_SPEED", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ECG_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "ECG_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ECG_SINUSOID_TEST", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "EST_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "EST_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "EST_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "EST_FREQUENCY", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "EST_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "EST_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "EST_INTENSITY", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "EST_PULSE_DURATION", decimalPlaces: 2, confidence: "medium", evidence: "override" },
  { code: "EST_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "EST_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "EST_TIMER", decimalPlaces: 0, confidence: "medium", evidence: "override" },
  { code: "EXLMP_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "EXLMP_CCT", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "EXLMP_CRI", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "EXLMP_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "EXLMP_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "EXLMP_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "EXLMP_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "EXLMP_INTENSITY", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "EXLMP_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "EXLMP_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "FDOP_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "FDOP_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "FDOP_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "FDOP_HR_ACCURACY", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "FDOP_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "FDOP_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "FDOP_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "FDOP_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "FM_FLOW_RATE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "FM_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "FM_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "HLAMP_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "HLAMP_CCT", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "HLAMP_CRI", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "HLAMP_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "HLAMP_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "HLAMP_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "HLAMP_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "HLAMP_INTENSITY", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "HLAMP_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "HLAMP_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "HUM_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "HUM_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "HUM_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "HUM_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "HUM_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "HUM_MAX_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "HUM_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "HUM_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "HUM_TEMP_ACCURACY", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "INCU_AIR_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "override" },
  { code: "INCU_AIR_VELOCITY", decimalPlaces: 2, confidence: "high", evidence: "override" },
  { code: "INCU_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "INCU_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "INCU_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "INCU_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "INCU_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "INCU_MATTRESS_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "INCU_NOISE_LEVEL", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "INCU_OVERSHOOT_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "INCU_RECOVERY_TIME", decimalPlaces: 0, confidence: "medium", evidence: "override" },
  { code: "INCU_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "INCU_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "INCU_SKIN_TEMP_SENSOR", decimalPlaces: 2, confidence: "medium", evidence: "override" },
  { code: "INFUS_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "INFUS_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "INFUS_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "INFUS_FLOW_RATE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "INFUS_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "INFUS_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "INFUS_OCCLUSION", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "INFUS_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "INFUS_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "IW_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "IW_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "IW_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "IW_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "IW_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "IW_MAX_MATTRESS_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "IW_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "IW_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "IW_TEMP_CALIBRATION", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "KVAK_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "KVAK_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "KVAK_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "KVAK_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "KVAK_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "KVAK_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "KVAK_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "KVAK_STORAGE_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "LAF_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LAF_DOWNFLOW", decimalPlaces: 2, confidence: "high", evidence: "override" },
  { code: "LAF_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "LAF_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LAF_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "LAF_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "LAF_LIGHT_INTENSITY", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "LAF_PARTICLE_COUNT", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "LAF_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "LAF_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "LAF_SOUND_LEVEL_BACKGROUND", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "LAF_SOUND_LEVEL_COMPARTMENT", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "LAF_UV_RADIATION", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LARYN_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LARYN_CCT", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LARYN_CRI", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "LARYN_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "LARYN_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LARYN_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "LARYN_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "LARYN_INTENSITY", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "LARYN_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "LARYN_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "LOP_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LOP_CCT", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LOP_CRI", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "LOP_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "LOP_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "LOP_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "LOP_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "LOP_INTENSITY", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "LOP_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "LOP_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "MFRZ_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "MFRZ_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "MFRZ_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "MFRZ_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "MFRZ_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "MFRZ_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "MFRZ_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "MFRZ_STORAGE_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "MICRO_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "MICRO_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "MICRO_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "MICRO_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "MICRO_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "MICRO_MAG_10X", decimalPlaces: 2, confidence: "low", evidence: "convention" },
  { code: "MICRO_MAG_4X", decimalPlaces: 2, confidence: "low", evidence: "convention" },
  { code: "MICRO_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "MICRO_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "MREF_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "MREF_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "MREF_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "MREF_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "MREF_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "MREF_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "MREF_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "MREF_STORAGE_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "NCOMP_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "NCOMP_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "NCOMP_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "NCOMP_FLOW_RATE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "NCOMP_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "NCOMP_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "NCOMP_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "NCOMP_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "O2CON_CONCENTRATION", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "O2CON_FLOW_RATE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "O2CON_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "O2CON_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "OVEN_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "OVEN_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "OVEN_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "OVEN_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "OVEN_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "OVEN_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "OVEN_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "OVEN_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "OXYM_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "OXYM_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "OXYM_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "OXYM_HEART_RATE", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "OXYM_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "OXYM_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "OXYM_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "OXYM_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "OXYM_SPO2", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "PHOTO_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PHOTO_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "PHOTO_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PHOTO_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PHOTO_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "PHOTO_IRRADIANCE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PHOTO_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "PHOTO_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PLT_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PLT_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "PLT_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PLT_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PLT_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "PLT_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "PLT_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PLT_STORAGE_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PM_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PM_DIASTOLIC", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "PM_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "PM_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PM_HEART_RATE", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "PM_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PM_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "PM_MAP", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "PM_RESP_RATE", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "PM_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "PM_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PM_SPO2", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "PM_SYSTOLIC", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "PULSEOX_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PULSEOX_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "PULSEOX_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "PULSEOX_HEART_RATE", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "PULSEOX_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PULSEOX_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "PULSEOX_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "PULSEOX_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "PULSEOX_SPO2", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "RESUS_C_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "RESUS_C_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "RESUS_C_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "RESUS_C_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "RESUS_C_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "RESUS_C_MAX_PRESSURE", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "RESUS_C_PRESSURE_ACC", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "RESUS_C_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "RESUS_C_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "RESUS_P_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "RESUS_P_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "RESUS_P_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "RESUS_P_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "RESUS_P_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "RESUS_P_MAX_PRESSURE", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "RESUS_P_PRESSURE_ACC", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "RESUS_P_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "RESUS_P_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ROT_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ROT_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "ROT_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "ROT_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ROT_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "ROT_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "ROT_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "ROT_SPEED", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "ROT_TIME", decimalPlaces: 0, confidence: "medium", evidence: "override" },
  { code: "RW_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "RW_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "RW_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "RW_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "RW_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "RW_MAX_MATTRESS_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "RW_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "RW_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "RW_TEMP_CALIBRATION", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "SPHYG_DEFLATION", decimalPlaces: 0, confidence: "medium", evidence: "override" },
  { code: "SPHYG_LEAK_TEST", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "SPHYG_PRESSURE_ACC", decimalPlaces: 0, confidence: "high", evidence: "setpoint" },
  { code: "SPHYG_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "SPHYG_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "SPIRO_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "SPIRO_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "SPIRO_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "SPIRO_FVC", decimalPlaces: 2, confidence: "medium", evidence: "override" },
  { code: "SPIRO_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "SPIRO_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "SPIRO_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "SPIRO_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "STER_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "STER_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "STER_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "STER_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "STER_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "STER_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "STER_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "STER_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "SUCT_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "SUCT_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "SUCT_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "SUCT_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "SUCT_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "SUCT_MAX_VACUUM", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "SUCT_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "SUCT_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "SUCT_TIME_MAX_VACUUM", decimalPlaces: 0, confidence: "medium", evidence: "override" },
  { code: "SUCT_VACUUM_GAUGE", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "SYR_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "SYR_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "SYR_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "SYR_FLOW_RATE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "SYR_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "SYR_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "SYR_OCCLUSION", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "SYR_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "SYR_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "UNEB_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "UNEB_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "UNEB_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "UNEB_FLOW_RATE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "UNEB_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "UNEB_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "UNEB_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "UNEB_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "VENT_APPLIED_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "VENT_EARTH_RESISTANCE", decimalPlaces: 2, confidence: "medium", evidence: "convention" },
  { code: "VENT_EQUIP_LEAKAGE", decimalPlaces: 1, confidence: "low", evidence: "convention" },
  { code: "VENT_EXP_TIME", decimalPlaces: 2, confidence: "medium", evidence: "override" },
  { code: "VENT_FIO2", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "VENT_INPUT_VOLTAGE", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "VENT_INSP_TIME", decimalPlaces: 2, confidence: "medium", evidence: "override" },
  { code: "VENT_INSULATION_RESISTANCE", decimalPlaces: 0, confidence: "low", evidence: "convention" },
  { code: "VENT_MINUTE_VOLUME", decimalPlaces: 2, confidence: "low", evidence: "convention" },
  { code: "VENT_PEEP", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "VENT_PPEAK", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "VENT_RESP_RATE", decimalPlaces: 0, confidence: "high", evidence: "convention" },
  { code: "VENT_ROOM_HUMIDITY", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
  { code: "VENT_ROOM_TEMP", decimalPlaces: 1, confidence: "medium", evidence: "convention" },
  { code: "VENT_TIDAL_VOLUME", decimalPlaces: 0, confidence: "medium", evidence: "convention" },
];

const RANK: Record<Confidence, number> = { high: 3, medium: 2, low: 1 };

async function main() {
  const minConf = (process.env.MIN_CONFIDENCE as Confidence) || "medium";
  if (!(minConf in RANK)) throw new Error(`MIN_CONFIDENCE must be high|medium|low, got ${minConf}`);
  const threshold = RANK[minConf];

  const codes = PROPOSALS.map((p) => p.code);
  if (new Set(codes).size !== codes.length) throw new Error("duplicate codes in PROPOSALS");

  const params = await prisma.deviceCalibrationParameter.findMany({
    where: { code: { in: codes } },
    select: { id: true, code: true, valueType: true, decimalPlaces: true },
  });
  const byCode = new Map(params.map((p) => [p.code, p]));

  let updated = 0;
  let skippedReviewed = 0;
  let skippedConfidence = 0;
  let skippedNonNumber = 0;
  const missing: string[] = [];

  for (const p of PROPOSALS) {
    const row = byCode.get(p.code);
    if (!row) { missing.push(p.code); continue; }
    if (row.valueType !== "NUMBER") { skippedNonNumber += 1; continue; }
    if (row.decimalPlaces != null && row.decimalPlaces !== 0) { skippedReviewed += 1; continue; }
    if (RANK[p.confidence] < threshold) { skippedConfidence += 1; continue; }
    if (row.decimalPlaces === p.decimalPlaces) continue; // already at target (0 == 0)
    await prisma.deviceCalibrationParameter.update({
      where: { id: row.id },
      data: { decimalPlaces: p.decimalPlaces },
    });
    updated += 1;
  }

  console.log(
    `[backfill-decimal-places] minConfidence=${minConf} updated=${updated} ` +
      `skipped(reviewed)=${skippedReviewed} skipped(confidence)=${skippedConfidence} ` +
      `skipped(nonNumber)=${skippedNonNumber}` +
      (missing.length ? ` missing=${missing.join(",")}` : ""),
  );
  await prisma.$disconnect();
}

main().catch((e) => { console.error(e); process.exit(1); });
