/**
 * Storage keys are generated by the application, never supplied by the caller
 * and never derived from the original filename. Layout:
 *
 *   {companyId}/{ownerType}/{ownerId}/{fileId}{ext}
 *
 * - company-scoped (tenant isolation visible on disk)
 * - opaque fileId (a UUID) guarantees no collision on same-named re-uploads
 * - every segment is validated against a strict allow-list, so `..`, path
 *   separators, NUL and absolute paths cannot appear
 */

const SEGMENT_RE = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;
const EXT_RE = /^\.[A-Za-z0-9]{1,12}$/;

export class InvalidStorageKeySegmentError extends Error {
  constructor(label: string) {
    super(`Invalid ${label} for a storage key`);
    this.name = "InvalidStorageKeySegmentError";
  }
}

function assertSegment(label: string, value: string): string {
  if (!value || value.length > 128 || value.includes("..") || !SEGMENT_RE.test(value)) {
    throw new InvalidStorageKeySegmentError(label);
  }
  return value;
}

function normalizeExtension(ext: string | null | undefined): string {
  if (!ext) return "";
  const withDot = ext.startsWith(".") ? ext : `.${ext}`;
  if (!EXT_RE.test(withDot)) throw new InvalidStorageKeySegmentError("extension");
  return withDot.toLowerCase();
}

export function buildStorageKey(input: {
  companyId: string;
  ownerType: string;
  ownerId: string;
  fileId: string;
  extension?: string | null;
}): string {
  return [
    assertSegment("companyId", input.companyId),
    assertSegment("ownerType", input.ownerType),
    assertSegment("ownerId", input.ownerId),
    assertSegment("fileId", input.fileId) + normalizeExtension(input.extension),
  ].join("/");
}
