import { BadRequestException } from "@nestjs/common";

/**
 * Validation of the EXTERNAL certificate number a user types when uploading a
 * certificate produced outside Medcal (source = UPLOADED). The number is the
 * external issuer's own identity for that certificate, so this validates
 * safety and identity only — it never imposes Medcal's PFX/YYYY/MM/NNNNN
 * shape on an external numbering convention.
 */
export const EXTERNAL_CERTIFICATE_NUMBER_MAX_LENGTH = 64;

// Letters, digits, and the separators real-world certificate numbers use.
// Must start with an alphanumeric. No control chars, quotes, or wildcards.
const EXTERNAL_NUMBER_CHARSET = /^[A-Za-z0-9][A-Za-z0-9 ._/-]*$/;

/**
 * `CRT/` is the identity namespace of Medcal-generated certificates
 * (DocumentType CERTIFICATE_GENERATED). Case-insensitive and tolerant of
 * whitespace before the slash so `crt/…` and `CRT /…` cannot sneak in.
 */
const RESERVED_GENERATED_NAMESPACE = /^crt\s*\//i;

/** C0/C1 controls, DEL, and the Unicode line/paragraph separators (U+2028/2029). */
function hasControlCharacter(value: string): boolean {
  for (const ch of value.trim()) {
    const c = ch.codePointAt(0) as number;
    if (c <= 0x1f || (c >= 0x7f && c <= 0x9f) || c === 0x2028 || c === 0x2029) return true;
  }
  return false;
}

export function isReservedGeneratedCertificateNumber(value: string): boolean {
  return RESERVED_GENERATED_NAMESPACE.test(value.trim());
}

/**
 * Trim, collapse internal whitespace runs to one space, and validate. The
 * meaningful characters — including their case — are preserved verbatim.
 * Uniqueness is enforced case-insensitively by the service (the DB index is
 * case-sensitive), so `abc-001` and `ABC-001` cannot both exist in a company.
 */
export function normalizeExternalCertificateNumber(raw: unknown): string {
  if (typeof raw !== "string") {
    throw new BadRequestException({
      code: "CERTIFICATE_NUMBER_REQUIRED",
      message: "The certificate number printed on the uploaded certificate is required",
    });
  }
  // Control characters (tab, newline, NUL, ...) and line/paragraph separators
  // never belong in a printed certificate number; reject rather than silently
  // rewriting them into spaces.
  if (hasControlCharacter(raw)) {
    throw new BadRequestException({
      code: "CERTIFICATE_NUMBER_INVALID",
      message: "The certificate number must not contain control or line-break characters",
    });
  }
  const value = raw.trim().replace(/\s+/g, " ");
  if (value.length === 0) {
    throw new BadRequestException({
      code: "CERTIFICATE_NUMBER_REQUIRED",
      message: "The certificate number printed on the uploaded certificate is required",
    });
  }
  if (value.length > EXTERNAL_CERTIFICATE_NUMBER_MAX_LENGTH) {
    throw new BadRequestException({
      code: "CERTIFICATE_NUMBER_TOO_LONG",
      message: `The certificate number must be at most ${EXTERNAL_CERTIFICATE_NUMBER_MAX_LENGTH} characters`,
    });
  }
  if (isReservedGeneratedCertificateNumber(value)) {
    throw new BadRequestException({
      code: "CERTIFICATE_NUMBER_RESERVED",
      message: 'Certificate numbers starting with "CRT/" are reserved for certificates generated by Medcal',
    });
  }
  if (!EXTERNAL_NUMBER_CHARSET.test(value)) {
    throw new BadRequestException({
      code: "CERTIFICATE_NUMBER_INVALID",
      message:
        "The certificate number may only contain letters, digits, spaces and . _ / - , and must start with a letter or digit",
    });
  }
  return value;
}
